---
- name: Install yq
  shell: |
    wget https://github.com/mikefarah/yq/releases/download/{{ yq_version }}/{{ yq_binary }}.tar.gz
    tar -xzf {{ yq_binary }}.tar.gz
    mv {{ yq_binary }} /usr/local/bin/
  args:
    creates: /usr/local/bin/yq
  become: true