- name: Add repository
  yum_repository:
    name: mongodb-org-4.2
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc
  become: yes

- package:
    name: mongodb-org
    state: present
  become: yes