---
- name: Install MongoDB
  include_tasks: "{{ item }}"
  with_first_found:
    - "install-{{ ansible_os_family }}.yml"
    - "install.yml"

- name: Check root password
  assert:
    that: mongodb_root_password != ''
    fail_msg: "You must specify a root password for MongoDB."
    quiet: yes

- name: Create conf directory
  file:
    path: "{{ mongodb_conf_path | dirname }}"
    recurse: yes
    state: directory
  become: true

- name: Create conf file
  template:
    src: templates/mongod.conf.j2
    dest: "{{ mongodb_conf_path }}"
    force: no
  become: true

- name: Add start/stop routines to ~/.bash_profile
  blockinfile:
    marker: "# MONGODB - {mark} ANSIBLE MANAGED BLOCK"
    block: "{{ lookup('file', 'templates/.bash_profile.j2') }}"
    dest: ~/.bash_profile
    backup: yes
  when: mongodb_create_aliases | bool

- name: Start MongoDB
  shell: "sudo -u {{ mongodb_user }} mongod -f {{ mongodb_conf_path }}"
  args:
    creates: "{{ mongodb_lock_path }}"
  become: true

- name: Ensure MongoDB is started
  shell: "[ \"$(cat {{ mongodb_lock_path }})\" != \"\" ] || sudo -u {{ mongodb_user }} mongod -f {{ mongodb_conf_path }}"
  register: result
  changed_when: result.stdout != ''
  become: true

- name: Create root user
  mongodb_user:
    database: admin
    name: root
    password: "{{ mongodb_root_password }}"
    roles: root
    state: present

# - name: Secure installation
#   lineinfile: dest={{ mongodb_conf_path }} line="auth = true"
#   become: true
#   when: "'admin.root' in hasRoot.stdout"

- name: Secure installation
  replace:
    dest: "{{ mongodb_conf_path }}"
    regexp: "^#security:.*"
    replace: "security:\n  authorization: enabled"
    backup: yes
  become: true

- name: Create mongorc file
  lineinfile:
    dest: ~/.mongorc.js
    line: db.getSiblingDB("admin").auth("root", "{{ mongodb_root_password }}");
    state: present
    create: yes

