---
- name: Check root password
  assert:
    that: mongodb_root_password != ''
    fail_msg: "You must specify a root password for MongoDB."
    quiet: yes

- name: Create /opt/local/etc/mongodb
  file:
    path: /opt/local/etc/mongodb
    recurse: yes
    state: directory
  become: true

- name: Create /opt/local/etc/mongodb/mongod.conf
  template:
    src: templates/mongod.conf.j2
    dest: /opt/local/etc/mongodb/mongod.conf
    force: no
  become: true

- name: Add start/stop routines to ~/.bash_profile
  blockinfile:
    marker: "# MONGODB - {mark} ANSIBLE MANAGED BLOCK"
    block: "{{ lookup('file', 'templates/.bash_profile.j2') }}"
    dest: ~/.bash_profile
    backup: yes

- name: Start MongoDB
  shell: mongod -f /opt/local/etc/mongodb/mongod.conf
  become: true
  args:
    creates: /opt/local/var/db/mongodb/mongod.lock

- name: Create root user
  shell: mongo admin -u root -p "{{ mongodb_root_password }}" --authenticationDatabase admin --eval "db.getUsers()" | grep "admin.root" || mongo admin --eval "db.createUser({user:'root',pwd:'{{ mongodb_root_password }}',roles:[{role:'root',db:'admin'}]});"
  register: hasRoot
  changed_when: "'Successfully added user' in hasRoot.stdout"
  failed_when: "'admin.root' not in hasRoot.stdout"

- name: Secure installation
  lineinfile: dest=/opt/local/etc/mongodb/mongod.conf line="auth = true"
  become: true
  when: "'admin.root' in hasRoot.stdout"

- name: Create mongorc file
  lineinfile:
    dest: ~/.mongorc.js
    line: db.getSiblingDB("admin").auth("root", "{{ mongodb_root_password }}");
    state: present
    create: yes
  when: "'admin.root' in hasRoot.stdout"

