---
- name: Install Apache
  include_tasks: "{{ item }}"
  with_first_found:
    - "install-{{ ansible_os_family }}.yml"
    - "install.yml"

- name: Configure Apache
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: yes
  with_items: "{{ apache_conf_items }}"
  become: true

# - name: Enable PHP module
#   shell: grep "^LoadModule php7_module" {{ apache_conf_path }}/httpd.conf || apxs -a -e -n php7 mod_php71.so
#   args:
#     chdir: "{{ apache_modules_path }}"
#   register: result
#   changed_when: "'activating' in result.stdout"
#   become: true

- name: Enable additional modules
  shell: grep "^LoadModule {{ item }}_module" {{ apache_conf_path }}/httpd.conf || apxs -a -e -n {{ item }} mod_{{ item }}.so
  args:
    chdir: "{{ apache_modules_path }}"
  register: result
  changed_when: "'activating' in result.stdout"
  with_items: "{{ apache_modules }}"
  become: true

- name: Add apache vhosts configuration
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/extra/{{ apache_vhosts_filename }}"
    backup: yes
  when: apache_create_vhosts | bool
  become: true

- name: Add vhosts to /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{ item.servername }}"
  with_items: "{{ apache_vhosts }}"
  when: apache_create_vhosts | bool
  become: true

- name: Start Apache
  include_tasks: "{{ item }}"
  with_first_found:
    - "start-{{ ansible_os_family }}.yml"
    - "start.yml"


