---
# global default configurations
ssh_enabled: false
ssl_enabled: false
apache_enabled: false
mariadb_enabled: false
php_enabled: false
mongodb_enabled: false
nvm_enabled: false
rbenv_enabled: false
chromedriver_enabled: false
mailcatcher_enabled: false