---
- hosts: all
  connection: local

  pre_tasks:
    - include_vars: "{{ os_family_vars }}"
      with_first_found:
        - files:
          - "vars/{{ ansible_os_family }}.yml"
          - "vars/Generic.yml"
      loop_control:
        loop_var: os_family_vars

    - include_vars: "{{ local_vars }}"
      with_items:
        - default.config.yml
        - config.yml
      loop_control:
        loop_var: local_vars

  tasks:
    - include_tasks: "{{ task_include }}"
      with_first_found:
        - "tasks/{{ ansible_os_family }}.yml"
        - "tasks/Unsupported.yml"
      loop_control:
        loop_var: task_include
