---

- name: Install yay
  include_role:
    name: yay
  when: yay_enabled
  tags:
    - yay

- name: SSH
  include_role:
    name: ssh
  when: ssh_enabled
  tags:
    - ssh

- name: MariaDB
  include_role:
    name: mariadb
  when: mariadb_enabled
  tags:
    - mariadb

- name: PHP
  include_role:
    name: php
  when: php_enabled
  tags:
    - php

- name: Apache
  include_role:
    name: apache
  when: apache_enabled
  tags:
    - apache

- name: NVM (Node.js)
  include_role:
    name: nvm
  when: nvm_enabled
  tags:
    - nvm

- name: MongoDB
  include_role:
    name: mongodb
  when: mongodb_enabled
  tags:
    - mongodb