---

- name: Install App Store applications
  include_role:
    name: mas
    when: mas_installed_apps

- name: OSX specific tasks (install wget, bash-completion)
  include_role:
    name: osx

- name: Install Git
  include_role: name=git
