---

- name: Add localhost entry to /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 localhost"
  become: true

- name: Add /opt/local/bin/bash to /etc/shells
  lineinfile: dest=/etc/shells line="/opt/local/bin/bash"
  become: true

- name: Create /etc/paths.d/00-macports
  lineinfile: dest=/etc/paths.d/00-macports line="/opt/local/bin" state=present create=yes
  become: true

- name: Install packages
  macports: name={{ item }} state=present
  with_items: "{{ packages }}"
  become: true

- name: Set login shell
  shell: chsh -s /opt/local/bin/bash
  when: lookup("env", "SHELL") != "/opt/local/bin/bash"

- name: Install App Store applications
  include_role:
    name: mas
  when: install_mas_apps and mas_installed_apps
