---

- name: Add entries to /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{ item }}"
  with_items:
    - localhost
    - local.com
  become: true

- name: Add /opt/local/bin/bash to /etc/shells
  lineinfile: dest=/etc/shells line="/opt/local/bin/bash"
  become: true

- name: Create /etc/paths.d/00-macports
  lineinfile: dest=/etc/paths.d/00-macports line="/opt/local/bin" state=present create=yes
  become: true

- name: Install App Store applications
  include_role:
    name: mas
  when: install_mas_apps and mas_installed_apps

- name: Install packages
  macports: name={{ item }} state=present
  with_items: "{{ packages }}"
  become: true

- name: Set login shell
  shell: 'chsh -s /opt/local/bin/bash {{ ansible_user_id }}'
  register: result
  changed_when: "'Changing shell' in result.stderr and 'no changes' not in result.stderr"
  become: true

- name: Configure SSH
  include_role:
    name: ssh

- name: Configure SSL
  include_role:
    name: ssl

- name: Configure MariaDB
  include_role:
    name: mariadb

- name: Configure PHP
  include_role:
    name: php

- name: Configure Apache
  include_role:
    name: apache

- name: Configure MongoDB
  include_role:
    name: mongodb

- name: Install Node.js
  include_role:
    name: nvm

- name: Install Ruby
  include_role:
    name: rbenv

- name: Install chromedriver
  include_role:
    name: chromedriver

- name: Install mailcatcher
  include_role:
    name: mailcatcher
