---

- lineinfile: dest=/etc/hosts line="127.0.0.1 localhost"
  become: true

- name: install packages
  macports: name={{ item }} state=present
  with_items: "{{ packages }}"
  become: true

- name: Install App Store applications
  include_role:
    name: mas
    when: mas_installed_apps
