---

- name: Install EPEL repository
  package:
    name: epel-release
    state: present
  become: true

- name: Configure MariaDB
  include_role:
    name: mariadb
  when: mariadb_enabled
  tags:
    - mariadb

- name: Configure PHP
  include_role:
    name: php
  when: php_enabled
  tags:
    - php

- name: Configure Apache
  include_role:
    name: apache
  when: apache_enabled
  tags:
    - apache