---

- name: Install EPEL repository
  package:
    name: epel-release
    state: present
  become: true
  when: install_epel

- name: SSH
  include_role:
    name: ssh
  when: ssh_enabled
  tags:
    - ssh

- name: SSL
  include_role:
    name: ssl
  when: ssl_enabled
  tags:
    - ssl

- name: MariaDB
  include_role:
    name: mariadb
  when: mariadb_enabled
  tags:
    - mariadb

- name: PHP
  include_role:
    name: php
  when: php_enabled
  tags:
    - php

- name: Apache
  include_role:
    name: apache
  when: apache_enabled
  tags:
    - apache

- name: NVM (Node.js)
  include_role:
    name: nvm
  when: nvm_enabled
  tags:
    - nvm

- name: MongoDB
  include_role:
    name: mongodb
  when: mongodb_enabled
  tags:
    - mongodb

- name: wkhtmltopdf
  include_role:
    name: wkhtmltopdf
  when: wkhtmltopdf_enabled
  tags:
    - wkhtmltopdf

- name: Docker
  include_role:
    name: docker
  when: docker_enabled
  tags:
    - docker

- name: jenkins
  include_role:
    name: jenkins
  when: jenkins_enabled
  tags:
    - jenkins

- name: yq
  include_role:
    name: yq
  when: yq_enabled
  tags:
    - yq