---

- name: Install EPEL repository
  package:
    name: epel-release
    state: present
  become: true

- name: Configure Apache
  include_role:
    name: apache
  when: apache_enabled
  tags:
    - apache

- name: Configure PHP
  include_role:
    name: php
  when: php_enabled
  tags:
    - php