---
- name: Ensure MAS is installed.
  package: name=mas state=installed
  become: true

- name: Get MAS account status
  shell: mas account
  register: mas_account_result
  failed_when: mas_account_result.rc > 1
  changed_when: false

- name: Sign in to MAS when email and password are provided.
  shell: 'mas signin "{{ mas_email }}" "{{ mas_password }}"'
  register: mas_signin_result
  when: mas_account_result.rc == 1 and mas_email != '' and mas_password != ''

- name: Ensure configured MAS apps are installed.
  shell: mas install "{{ item.id }}"
  register: result
  changed_when: "'already installed' not in result.stdout"
  with_items: "{{ mas_installed_apps }}"

- name: Upgrade all apps (if configured).
  command: mas upgrade
  when: mas_upgrade_all_apps
