- shell: curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash -s -- --mariadb-server-version="mariadb-10.2"
  become: true

- package:
    name: mariadb-server
    state: present
  become: true