- shell: curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash -s -- --mariadb-server-version="mariadb-10.2"
  become: true

- package:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-server
    - python2-PyMySQL
  become: true