---
- name: Install MariaDB
  include_tasks: "{{ item }}"
  with_first_found:
    - "install-{{ ansible_os_family }}.yml"
    - "install.yml"

- name: Configure my.cnf
  template:
    src: "{{ mariadb_conf_template }}"
    dest: "{{ mariadb_conf_path }}"
    backup: yes
  become: yes

- name: Create encryption keyfile directory
  file:
    path: "{{ mariadb_encryption_conf_dir }}"
    state: directory
  become: yes

- name: Create encryption keyfile
  shell: echo "1;$(openssl rand -hex 32)" >> {{ mariadb_encryption_conf_dir }}/keyfile
  args:
    creates: "{{ mariadb_encryption_conf_dir }}/keyfile"
  become: true

- name: Setup data directory
  shell: "[ $(ls -1q {{ mariadb_data_dir }} | wc -l) -gt '0' ] || mysql_install_db --user=mysql --datadir={{ mariadb_data_dir }}"
  register: result
  changed_when: "'Installing MariaDB' in result.stdout"
  become: yes

- name: Start MariaDB
  include_tasks: "{{ item }}"
  with_first_found:
    - "start-{{ ansible_os_family }}.yml"
    - "start.yml"

- name: Set root password
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host_all: yes
    login_unix_socket: "{{ (mariadb_socket_auth == true) | ternary(mariadb_socket_path, '') }}"
  become: yes
  when: mariadb_root_password != ''

- name: Configure ~/.my.cnf
  ini_file:
    path: ~/.my.cnf
    section: client
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items:
    - option: user
      value:  root
    - option: password
      value: "{{ mariadb_root_password }}"
  when: mariadb_root_password != ''

- name: Remove anonymous users
  mysql_user:
    name: ""
    host_all: yes
    state: absent
    login_unix_socket: "{{ (mariadb_socket_auth == true) | ternary(mariadb_socket_path, '') }}"
  become: yes

- name: Disallow remote root login
  shell: mysql -NBe "{{ item }}"
  with_items:
    - DELETE FROM mysql.user WHERE User='root' And Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false
  become: yes

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_unix_socket: "{{ (mariadb_socket_auth == true) | ternary(mariadb_socket_path, '') }}"
  become: yes