---
- name: Install MariaDB
  include_tasks: "{{ item }}"
  with_first_found:
    - "install-{{ ansible_os_family }}.yml"
    - "install.yml"

- name: Configure my.cnf
  template:
    src: "{{ mariadb_conf_template }}"
    dest: "{{ mariadb_conf_path }}"
    backup: yes
  become: yes

- name: Setup data directory
  shell: "[ $(ls -1q {{ mariadb_data_dir }} | wc -l) -gt '0' ] || mysql_install_db"
  register: result
  changed_when: "'Installing MariaDB' in result.stdout"

- name: Start MariaDB
  include_tasks: "{{ item }}"
  with_first_found:
    - "start-{{ ansible_os_family }}.yml"
    - "start.yml"

- name: Set root password
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host_all: yes

- name: Configure ~/.my.cnf
  ini_file:
    path: ~/.my.cnf
    section: client
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items:
    - option: user
      value:  root
    - option: password
      value: "{{ mariadb_root_password }}"

- name: Get list of hosts for the anonymous user
  shell: mysql -NBe "SELECT Host FROM mysql.user WHERE User=''"
  register: mariadb_anonymous_hosts
  changed_when: false
  check_mode: false

- name: Remove anonymous users
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items: "{{ mariadb_anonymous_hosts.stdout_lines|default([]) }}"

- name: Disallow remote root login
  shell: mysql -NBe "{{ item }}"
  with_items:
    - DELETE FROM mysql.user WHERE User='root' And Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Remove test database
  mysql_db:
    name: test
    state: absent