- name: Add repository
  yum_repository:
    name: jenkins
    description: Jenkins Repository
    baseurl: http://pkg.jenkins-ci.org/redhat-stable/
    gpgcheck: yes
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  become: yes

- package:
    name: "{{ item }}"
    state: present
  with_items:
    - jenkins
  become: yes

- name: Set systemd environment variables
  lineinfile:
    path: /usr/lib/systemd/system/jenkins.service
    regexp: '^Environment="JAVA_OPTS='
    line: Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
  become: yes