---
- name: Create /etc/ssl/certs
  file:
    path: /etc/ssl/certs
    recurse: yes
    state: directory
  become: true

- name: Create root CA
  shell: |
    openssl genrsa -des3 -out rootCA.key 2048
    openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.pem
    security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain rootCA.pem
  args:
    chdir: /etc/ssl/certs
    creates: /etc/ssl/certs/rootCA.pem
  become: true

- name: Create server.csr.cnf
  template:
    src: server.csr.cnf.j2
    dest: /etc/ssl/certs/server.csr.cnf
    force: no
  become: true

- name: Create v3.ext
  template:
    src: v3.ext.j2
    dest: /etc/ssl/certs/v3.ext
    force: no
  become: true

- name: Generate localhost certificate
  shell: |
    openssl req -new -sha256 -nodes -out server.csr -newkey rsa:2048 -keyout server.key -config server.csr.cnf
    openssl x509 -req -in server.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out server.crt -days 500 -sha256 -extfile v3.ext
  args:
    chdir: /etc/ssl/certs
    creates: /etc/ssl/certs/server.crt
  become: true