---
apache_autostart: true
apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443

apache_conf_path: "/etc/httpd/conf"
apache_modules_path: "/etc/httpd/modules"

apache_documentroot: "/var/www/html"

apache_conf_items:
  - regexp: "^#?ServerName .*"
    line: "ServerName localhost:{{ apache_listen_port }}"
  - regexp: "^DocumentRoot .*"
    line: 'DocumentRoot "{{ apache_documentroot }}"'
  - regexp: '^<Directory "((?!cgi).)*">'
    line: '<Directory "{{ apache_documentroot }}">'

apache_modules:
  - deflate
  - expires
  - proxy
  - proxy_fcgi
  - rewrite
  - ssl

apache_create_vhosts: false
apache_vhosts_filename: "httpd-vhosts.conf"
apache_vhosts_template: "httpd-vhosts.conf.j2"
apache_vhosts: []

apache_ssl_protocol: "All -SSLv2 -SSLv3"
apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"