- package:
    name: "{{ item }}"
    state: present
  with_items:
    - php71
    - php71-fpm
    - php71-curl
    - php71-exif
    - php71-fpm
    - php71-gd
    - php71-gmp
    - php71-iconv
    - php71-imagick
    - php71-intl
    - php71-mbstring
    - php71-mcrypt
    - php71-mongodb
    - php71-mysql
    - php71-openssl
    - php71-pear
    - php71-posix
    - php71-soap
    - php71-xdebug
    - php71-yaml
    - php71-zip
    - wget
  become: true