- package:
    name: "{{ item }}"
    state: present
  with_items:
    - php{{ php_version | replace('.', '') }}
    - php{{ php_version | replace('.', '') }}-fpm
    - php{{ php_version | replace('.', '') }}-curl
    - php{{ php_version | replace('.', '') }}-excimer
    - php{{ php_version | replace('.', '') }}-exif
    - php{{ php_version | replace('.', '') }}-fpm
    - php{{ php_version | replace('.', '') }}-gd
    - php{{ php_version | replace('.', '') }}-gmp
    - php{{ php_version | replace('.', '') }}-iconv
    - php{{ php_version | replace('.', '') }}-imagick
    - php{{ php_version | replace('.', '') }}-intl
    - php{{ php_version | replace('.', '') }}-mbstring
    - php{{ php_version | replace('.', '') }}-mcrypt
    - php{{ php_version | replace('.', '') }}-mongodb
    - php{{ php_version | replace('.', '') }}-mysql
    - php{{ php_version | replace('.', '') }}-openssl
    - php{{ php_version | replace('.', '') }}-pear
    - php{{ php_version | replace('.', '') }}-pgsql
    - php{{ php_version | replace('.', '') }}-posix
    - php{{ php_version | replace('.', '') }}-soap
    - php{{ php_version | replace('.', '') }}-xdebug
    - php{{ php_version | replace('.', '') }}-yaml
    - php{{ php_version | replace('.', '') }}-zip
    - wget
  become: true
