---
- package:
    name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present
  become: true

- yum_repository:
    name: remi-php{{ php_version | replace('.', '') }}
    description: Remi's PHP {{ php_version }} RPM repository for Enterprise Linux 7 - $basearch
    mirrorlist: http://cdn.remirepo.net/enterprise/7/php{{ php_version | replace('.', '') }}/mirror
    enabled: yes
    gpgcheck: 1
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi
  become: true

- name: PHP packages
  package:
    name: "{{ php_pkg }}"
    state: present
  with_items:
    - php
    - php-common
    - php-fpm
    - php-gd
    - php-gmp
    - php-intl
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pecl-excimer
    - php-pecl-gnupg
    - php-pecl-imagick
    - php-pecl-mongodb
    - php-pecl-redis
    - php-pecl-xdebug
    - php-pecl-yaml
    - php-pecl-zip
    - php-pgsql
    - php-posix
    - php-soap
    - php-xml
    - wget
  loop_control:
    loop_var: php_pkg
  become: true

- name: Additional PHP 7 packages
  package:
    name: "{{ php7_pkg }}"
    state: present
  with_items:
    - php-ast
  loop_control:
    loop_var: php7_pkg
  when: php_version[0] == "7"
  become: true
