---
- package:
    name: "http://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    state: present
  become: true

- name: PHP packages
  package:
    name: "{{ php_pkg }}"
    state: present
  with_items:
    - php
    - php-common
    - php-fpm
    - php-gd
    - php-gmp
    - php-intl
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pecl-excimer
    - php-pecl-gnupg
    - php-pecl-imagick
    - php-pecl-mongodb
    - php-pecl-redis
    - php-pecl-xdebug
    - php-pecl-yaml
    - php-pecl-zip
    - php-pgsql
    - php-posix
    - php-soap
    - php-xml
    - wget
  loop_control:
    loop_var: php_pkg
  become: true

- name: Additional PHP 7 packages
  package:
    name: "{{ php7_pkg }}"
    state: present
  with_items:
    - php-ast
  loop_control:
    loop_var: php7_pkg
  when: php_version[0] == "7"
  become: true
