---
- package:
    name: " http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present
  become: true

- ini_file:
    path: /etc/yum.repos.d/remi-php71.repo
    section: remi-php71
    option: enabled
    value: 1

- package:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-common
    - php-fpm
    - php-gd
    - php-gmp
    - php-intl
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pecl-imagick
    - php-pecl-mongodb
    - php-soap
    - php-pecl-xdebug
    - php-pecl-yaml
    - php-pecl-zip
  become: true