---
- name: Install PHP
  include_tasks: "{{ item }}"
  with_first_found:
    - "install-{{ ansible_os_family }}.yml"
    - "install.yml"

- name: Create php.ini
  copy:
    src: "{{ php_ini_path }}-development"
    dest: "{{ php_ini_path }}"
    force: no
  become: yes

- name: Configure php.ini
  ini_file:
    path: "{{ php_ini_path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: no
    backup: yes
  with_items: "{{ php_ini_settings }}"
  become: yes

- name: Download Composer
  shell: command -v composer || ./bin/php/install-composer.sh
  register: result
  changed_when: result.stdout == ''

- name: Install Composer
  shell: cp composer.phar {{ php_composer_path }}
  args:
    creates: "{{ php_composer_path }}"
  become: yes

- name: Remove downloaded files
  file:
    path: composer.phar
    state: absent

- name: Update Composer
  shell: composer selfupdate
  register: result
  changed_when: "'Updating' in result.stdout"
  become: yes